-- Расширения для PostgreSQL (добавить в начало, если не созданы)
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email)
);

-- Таблица запросов на вещи
CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    description TEXT NOT NULL,
    requestor_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_request_on_requestor FOREIGN KEY (requestor_id)
        REFERENCES users(id) ON DELETE CASCADE
);

-- Таблица вещей
CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    is_available BOOLEAN NOT NULL DEFAULT true,
    owner_id BIGINT NOT NULL,
    request_id BIGINT,
    CONSTRAINT fk_item_on_owner FOREIGN KEY (owner_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_item_name_length CHECK (LENGTH(TRIM(name)) >= 1),
    CONSTRAINT chk_description_length CHECK (LENGTH(TRIM(description)) >= 1)
);

-- Таблица бронирований
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'WAITING',
    item_id BIGINT NOT NULL,
    booker_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_on_item FOREIGN KEY (item_id)
        REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_on_booker FOREIGN KEY (booker_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT valid_dates CHECK (end_date > start_date),
    CONSTRAINT valid_status CHECK (status IN ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED'))
);

-- Таблица комментариев
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    text TEXT NOT NULL,
    item_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comment_on_item FOREIGN KEY (item_id)
        REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_on_author FOREIGN KEY (author_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_comment_text_length CHECK (LENGTH(TRIM(text)) >= 1)
);

-- users
CREATE INDEX IF NOT EXISTS idx_users_email_lower ON users(LOWER(email));

-- requests
CREATE INDEX IF NOT EXISTS idx_requests_requestor_id ON requests(requestor_id);
CREATE INDEX IF NOT EXISTS idx_requests_created ON requests(created DESC);
CREATE INDEX IF NOT EXISTS idx_requests_requestor_created ON requests(requestor_id, created DESC);

-- items
CREATE INDEX IF NOT EXISTS idx_items_owner_id ON items(owner_id);
CREATE INDEX IF NOT EXISTS idx_items_request_id ON items(request_id) WHERE request_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_items_available ON items(is_available) WHERE is_available = true;
CREATE INDEX IF NOT EXISTS idx_items_owner_available ON items(owner_id, is_available);
CREATE INDEX IF NOT EXISTS idx_items_name_trgm ON items USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_items_description_trgm ON items USING gin (description gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_items_owner_available_id ON items(owner_id, is_available, id DESC);

-- bookings
CREATE INDEX IF NOT EXISTS idx_bookings_item_id ON bookings(item_id);
CREATE INDEX IF NOT EXISTS idx_bookings_booker_id ON bookings(booker_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_dates ON bookings(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_bookings_booker_dates ON bookings(booker_id, start_date DESC, end_date DESC);
CREATE INDEX IF NOT EXISTS idx_bookings_item_status_dates ON bookings(item_id, status, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_bookings_created ON bookings(created DESC);
CREATE INDEX IF NOT EXISTS idx_bookings_current ON bookings(item_id, status)
    WHERE status = 'APPROVED' AND end_date > CURRENT_TIMESTAMP;

-- comments
CREATE INDEX IF NOT EXISTS idx_comments_item_id ON comments(item_id);
CREATE INDEX IF NOT EXISTS idx_comments_author_id ON comments(author_id);
CREATE INDEX IF NOT EXISTS idx_comments_item_created ON comments(item_id, created DESC);
CREATE INDEX IF NOT EXISTS idx_comments_created ON comments(created DESC);

-- Настройки для таблиц с частыми обновлениями
ALTER TABLE bookings SET (
    autovacuum_vacuum_scale_factor = 0.05,
    autovacuum_vacuum_threshold = 1000,
    autovacuum_analyze_scale_factor = 0.02,
    autovacuum_analyze_threshold = 500
);

ALTER TABLE items SET (
    autovacuum_vacuum_scale_factor = 0.1,
    autovacuum_vacuum_threshold = 500
);